"""
LinkWatcher PhiUSIIL meta-gate calibration experiment.

This script is intentionally test/calibration-only:
- It does NOT retrain transformer_final.py.
- It does NOT modify app.py.
- It does NOT mix PhiUSIIL into the Kaggle 4-class training set.
- It loads the existing artifacts_transformer through app.py and keeps them fixed.

Purpose:
- Use PhiUSIIL only as an external benign/phishing calibration/test dataset.
- Learn a small post-hoc meta-gate that reduces benign -> phishing false positives,
  especially for short or unfamiliar legitimate URLs.
- Save artifacts that can be wired into app.py later if the experiment is good.

Required input:
- artifacts_transformer/ generated by transformer_final.py
- PhiUSIIL_Phishing_URL_Dataset.csv with columns URL,label
  Official mapping: label 1 = legitimate/benign, label 0 = phishing

Outputs:
- artifacts_phiusiil_meta_gate/
  - meta_gate.joblib
  - meta_gate_scaler.joblib
  - config.json
- results_phiusiil_meta_gate/
  - threshold_search_results.csv
  - external_test_predictions.csv
  - summary.json
"""

import json
import os
import re
import urllib.parse

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import app as inference_app


SEED = 42

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(PROJECT_DIR)

PHIUSIIL_CANDIDATE_PATHS = [
    os.path.join(PROJECT_DIR, "PhiUSIIL_Phishing_URL_Dataset.csv"),
    os.path.join(PARENT_DIR, "PhiUSIIL_Phishing_URL_Dataset.csv"),
]
MAIN_DATA_PATH = os.path.join(PROJECT_DIR, "malicious_phish.csv")

ARTIFACT_DIR = os.path.join(PROJECT_DIR, "artifacts_phiusiil_meta_gate")
RESULT_DIR = os.path.join(PROJECT_DIR, "results_phiusiil_meta_gate")

URL_COL = "url"
LABEL_COL = "type"
BENIGN_LABEL = "benign"
PHISHING_LABEL = "phishing"

# Full PhiUSIIL is large. These caps keep the experiment practical while still
# giving enough short legitimate URLs to calibrate the service decision layer.
CALIBRATION_RATIO = 0.70
MAX_CALIBRATION_EACH = 30000
MAX_EXTERNAL_TEST_EACH = 15000
INFERENCE_BATCH_SIZE = 512

# Higher penalty means "avoid false phishing alarms on benign URLs".
META_FP_PENALTY = 0.85
META_CLASS_WEIGHT = {0: 1.6, 1: 1.0}

THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

os.makedirs(ARTIFACT_DIR, exist_ok=True)
os.makedirs(RESULT_DIR, exist_ok=True)


def resolve_phiusiil_path():
    for path in PHIUSIIL_CANDIDATE_PATHS:
        if os.path.exists(path):
            return path

    raise FileNotFoundError(
        "PhiUSIIL_Phishing_URL_Dataset.csv not found. Checked:\n"
        + "\n".join(PHIUSIIL_CANDIDATE_PATHS)
    )


def clean_url_text(url):
    if url is None:
        url = ""

    url = str(url).strip().lower()

    try:
        url = urllib.parse.unquote(url, errors="ignore")
    except Exception:
        pass

    url = url.replace("[", "").replace("]", "")
    url = re.sub(r"[\x00-\x1f\x7f]", "", url)

    return url


def safe_parse_url(url):
    cleaned = clean_url_text(url)

    try:
        parse_target = cleaned
        if not re.match(r"^[a-zA-Z][a-zA-Z0-9+\-.]*://", parse_target):
            parse_target = "http://" + parse_target
        return urllib.parse.urlparse(parse_target)
    except Exception:
        return urllib.parse.urlparse("http://invalid.local/")


def normalize_phi_label(label):
    """
    PhiUSIIL official mapping:
    1 -> legitimate URL -> benign
    0 -> phishing URL
    """
    s = str(label).strip().lower()

    if s in {"1", "1.0", "legitimate", "legit", "benign", "safe", "normal"}:
        return BENIGN_LABEL

    if s in {"0", "0.0", "phishing", "phish", "malicious"}:
        return PHISHING_LABEL

    return None


def load_phiusiil_binary_dataset():
    path = resolve_phiusiil_path()
    df = pd.read_csv(path, usecols=["URL", "label"])
    df = df.rename(columns={"URL": URL_COL, "label": LABEL_COL})
    df[URL_COL] = df[URL_COL].astype(str).map(clean_url_text)
    df[LABEL_COL] = df[LABEL_COL].map(normalize_phi_label)
    df = df.dropna(subset=[URL_COL, LABEL_COL])
    df = df[df[LABEL_COL].isin([BENIGN_LABEL, PHISHING_LABEL])].copy()
    df = df.drop_duplicates(subset=[URL_COL]).reset_index(drop=True)

    if os.path.exists(MAIN_DATA_PATH):
        main_urls = pd.read_csv(MAIN_DATA_PATH, usecols=[URL_COL])[URL_COL]
        main_urls = set(main_urls.astype(str).map(clean_url_text))
        before = len(df)
        df = df[~df[URL_COL].isin(main_urls)].copy().reset_index(drop=True)
        print(f"Removed URL overlap with malicious_phish.csv: {before - len(df)}")

    print("\n[PhiUSIIL external dataset]")
    print("Path:", path)
    print("Rows:", len(df))
    print(df[LABEL_COL].value_counts())

    return df


def balanced_sample(df, max_each, random_state):
    parts = []

    for label in [BENIGN_LABEL, PHISHING_LABEL]:
        group = df[df[LABEL_COL] == label]
        n = min(len(group), max_each)
        parts.append(group.sample(n=n, random_state=random_state))

    sampled = pd.concat(parts, axis=0)
    sampled = sampled.sample(frac=1.0, random_state=random_state).reset_index(drop=True)

    return sampled


def split_external_dataset(df):
    calibration_df, test_df = train_test_split(
        df,
        train_size=CALIBRATION_RATIO,
        random_state=SEED,
        stratify=df[LABEL_COL],
    )

    calibration_df = balanced_sample(
        calibration_df,
        max_each=MAX_CALIBRATION_EACH,
        random_state=SEED + 1,
    )
    test_df = balanced_sample(
        test_df,
        max_each=MAX_EXTERNAL_TEST_EACH,
        random_state=SEED + 2,
    )

    print("\n[Calibration split]")
    print(calibration_df[LABEL_COL].value_counts())
    print("\n[External test split]")
    print(test_df[LABEL_COL].value_counts())

    return calibration_df, test_df


def url_policy_features(urls):
    rows = []

    for url in urls:
        u = clean_url_text(url)
        parsed = safe_parse_url(u)
        host = inference_app.get_normalized_host(u)
        path = parsed.path or ""
        query = parsed.query or ""
        domain_parts = [p for p in host.split(".") if p]

        known_safe_domain = inference_app.matched_known_safe_domain(host)
        known_safe_risky = inference_app.has_strong_known_safe_risk_signal(u)

        rows.append([
            float(len(u)),
            float(len(host)),
            float(len(path)),
            float(len(query)),
            float(u.count(".")),
            float(u.count("-")),
            float(u.count("_")),
            float(u.count("@")),
            float(u.count("%")),
            float(u.count("=")),
            float(u.count("&")),
            float(len(domain_parts)),
            1.0 if query else 0.0,
            1.0 if path and path != "/" else 0.0,
            1.0 if (not path or path == "/") and not query else 0.0,
            1.0 if len(u) <= 35 else 0.0,
            1.0 if len(u) <= 50 else 0.0,
            1.0 if known_safe_domain is not None else 0.0,
            1.0 if known_safe_risky else 0.0,
            1.0 if host.endswith(".ac.kr") or host.endswith(".edu") else 0.0,
            1.0 if host.endswith(".go.kr") or host.endswith(".gov") else 0.0,
            1.0 if host.endswith(".co.kr") else 0.0,
        ])

    return np.array(rows, dtype=np.float32)


def iter_batches(items, batch_size):
    for start in range(0, len(items), batch_size):
        yield start, items[start:start + batch_size]


def predict_transformer_probs_batched(urls, batch_size=INFERENCE_BATCH_SIZE):
    chunks = []

    for _, batch_urls in iter_batches(urls, batch_size):
        chunks.append(inference_app.predict_transformer_phishing_probs(batch_urls))

    if not chunks:
        return np.array([], dtype=np.float32)

    return np.concatenate(chunks).astype(np.float32)


def extract_meta_features(urls):
    benign_id = inference_app.benign_id
    phishing_id = inference_app.phishing_id

    rows = []
    base_proba_chunks = []
    base_pred_chunks = []
    transformer_chunks = []

    for batch_idx, batch_urls in iter_batches(urls, INFERENCE_BATCH_SIZE):
        print(f"  feature batch {batch_idx // INFERENCE_BATCH_SIZE + 1} / {int(np.ceil(len(urls) / INFERENCE_BATCH_SIZE))}")

        x_base = inference_app.build_features(batch_urls)
        base_proba = inference_app.base_model.predict_proba(x_base)
        base_pred = np.argmax(base_proba, axis=1)
        transformer_probs = predict_transformer_probs_batched(batch_urls)

        sorted_probs = np.sort(base_proba, axis=1)
        top_margin = sorted_probs[:, -1] - sorted_probs[:, -2]
        policy = url_policy_features(batch_urls)

        base_proba_chunks.append(base_proba)
        base_pred_chunks.append(base_pred)
        transformer_chunks.append(transformer_probs)

        for i in range(len(batch_urls)):
            base_benign = float(base_proba[i][benign_id])
            base_phishing = float(base_proba[i][phishing_id])
            transformer_phishing = float(transformer_probs[i])

            row = [
                base_benign,
                base_phishing,
                base_phishing - base_benign,
                abs(base_phishing - base_benign),
                float(np.max(base_proba[i])),
                float(top_margin[i]),
                1.0 if base_pred[i] == benign_id else 0.0,
                1.0 if base_pred[i] == phishing_id else 0.0,
                transformer_phishing,
                transformer_phishing - base_phishing,
                abs(transformer_phishing - base_phishing),
            ]
            row.extend(policy[i].tolist())
            rows.append(row)

    return (
        np.array(rows, dtype=np.float32),
        np.vstack(base_proba_chunks),
        np.concatenate(base_pred_chunks),
        np.concatenate(transformer_chunks),
    )


META_FEATURE_NAMES = [
    "base_benign_prob",
    "base_phishing_prob",
    "base_phishing_minus_benign",
    "base_benign_phishing_margin",
    "base_top_prob",
    "base_top_margin",
    "base_pred_is_benign",
    "base_pred_is_phishing",
    "transformer_phishing_prob",
    "transformer_minus_base_phishing",
    "transformer_base_abs_gap",
    "url_length",
    "host_length",
    "path_length",
    "query_length",
    "dot_count",
    "hyphen_count",
    "underscore_count",
    "at_count",
    "percent_count",
    "equal_count",
    "amp_count",
    "domain_part_count",
    "has_query",
    "has_path",
    "root_or_empty_path",
    "short_url_le35",
    "short_url_le50",
    "known_safe_domain_flag",
    "known_safe_risky_signal",
    "education_tld_flag",
    "government_tld_flag",
    "korea_company_tld_flag",
]


def current_app_predictions(urls):
    preds = []

    for _, batch_urls in iter_batches(urls, INFERENCE_BATCH_SIZE):
        results, _ = inference_app.hybrid_predict(batch_urls)
        preds.extend([
            1 if row["prediction"] == PHISHING_LABEL else 0
            for row in results
        ])

    return np.array(preds, dtype=int)


def find_best_threshold(y_true, scores):
    rows = []
    best = None

    for threshold in np.arange(THRESHOLD_MIN, THRESHOLD_MAX + 1e-9, THRESHOLD_STEP):
        y_pred = (scores >= threshold).astype(int)
        precision = precision_score(y_true, y_pred, zero_division=0)
        recall = recall_score(y_true, y_pred, zero_division=0)
        f1 = f1_score(y_true, y_pred, zero_division=0)

        benign_fp = int(np.sum((y_true == 0) & (y_pred == 1)))
        benign_total = int(np.sum(y_true == 0))
        benign_fp_rate = benign_fp / max(benign_total, 1)

        objective = f1 - META_FP_PENALTY * benign_fp_rate
        row = {
            "threshold": float(threshold),
            "precision": float(precision),
            "recall": float(recall),
            "f1": float(f1),
            "benign_fp": benign_fp,
            "benign_total": benign_total,
            "benign_fp_rate": float(benign_fp_rate),
            "objective": float(objective),
        }
        rows.append(row)

        if best is None or objective > best["objective"]:
            best = row

    return best, pd.DataFrame(rows)


def evaluate_binary(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])

    return {
        "title": title,
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "phishing_precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "phishing_recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "phishing_f1": float(f1_score(y_true, y_pred, zero_division=0)),
        "benign_recall": float(recall_score(y_true, y_pred, pos_label=0, zero_division=0)),
        "benign_to_phishing": int(cm[0][1]),
        "phishing_to_benign": int(cm[1][0]),
        "confusion_matrix": cm.tolist(),
        "classification_report": classification_report(
            y_true,
            y_pred,
            target_names=[BENIGN_LABEL, PHISHING_LABEL],
            output_dict=True,
            zero_division=0,
        ),
    }


def print_report(report):
    print(f"\n[{report['title']}]")
    print("Accuracy:", round(report["accuracy"], 4))
    print("Benign recall:", round(report["benign_recall"], 4))
    print(
        "Phishing P/R/F1:",
        round(report["phishing_precision"], 4),
        round(report["phishing_recall"], 4),
        round(report["phishing_f1"], 4),
    )
    print("Benign -> Phishing:", report["benign_to_phishing"])
    print("Phishing -> Benign:", report["phishing_to_benign"])
    print("Confusion matrix [0=benign, 1=phishing]:")
    print(np.array(report["confusion_matrix"]))


def debug_urls(meta_gate, scaler, threshold):
    urls = [
        "https://www.airbnb.co.kr/",
        "https://www.dankook.ac.kr/",
        "https://www.tistory.com/",
        "https://notice.tistory.com/",
        "https://www.google.com/",
        "https://www.naver.com/",
        "https://www.11st.co.kr/main",
        "https://google.com.verify-login-security.xyz",
    ]

    x_raw, _, _, transformer_probs = extract_meta_features(urls)
    x = scaler.transform(x_raw)
    scores = meta_gate.predict_proba(x)[:, 1]
    current_pred = current_app_predictions(urls)
    meta_pred = (scores >= threshold).astype(int)

    rows = []
    for i, url in enumerate(urls):
        rows.append({
            "url": url,
            "current_app_prediction": PHISHING_LABEL if current_pred[i] else BENIGN_LABEL,
            "meta_gate_prediction": PHISHING_LABEL if meta_pred[i] else BENIGN_LABEL,
            "meta_phishing_score": float(scores[i]),
            "threshold": float(threshold),
            "transformer_phishing_probability": float(transformer_probs[i]),
        })

    return rows


def main():
    phi_df = load_phiusiil_binary_dataset()
    calibration_df, test_df = split_external_dataset(phi_df)

    calibration_urls = calibration_df[URL_COL].tolist()
    test_urls = test_df[URL_COL].tolist()
    y_cal = (calibration_df[LABEL_COL].values == PHISHING_LABEL).astype(int)
    y_test = (test_df[LABEL_COL].values == PHISHING_LABEL).astype(int)

    print("\nExtracting calibration features with fixed existing model...")
    x_cal_raw, _, _, _ = extract_meta_features(calibration_urls)

    print("Extracting external test features with fixed existing model...")
    x_test_raw, _, _, test_transformer_probs = extract_meta_features(test_urls)

    meta_scaler = StandardScaler()
    x_cal = meta_scaler.fit_transform(x_cal_raw)
    x_test = meta_scaler.transform(x_test_raw)

    meta_gate = LogisticRegression(
        class_weight=META_CLASS_WEIGHT,
        max_iter=1000,
        random_state=SEED,
        solver="lbfgs",
    )
    meta_gate.fit(x_cal, y_cal)

    cal_scores = meta_gate.predict_proba(x_cal)[:, 1]
    best_threshold, threshold_df = find_best_threshold(y_cal, cal_scores)

    threshold_path = os.path.join(RESULT_DIR, "threshold_search_results.csv")
    threshold_df.to_csv(threshold_path, index=False)

    test_scores = meta_gate.predict_proba(x_test)[:, 1]
    y_meta = (test_scores >= best_threshold["threshold"]).astype(int)
    y_current = current_app_predictions(test_urls)

    current_report = evaluate_binary(y_test, y_current, "current_app_hybrid_on_phiusiil_test")
    meta_report = evaluate_binary(y_test, y_meta, "meta_gate_on_phiusiil_test")
    debug_rows = debug_urls(meta_gate, meta_scaler, best_threshold["threshold"])

    predictions_df = pd.DataFrame({
        "url": test_urls,
        "true_label": test_df[LABEL_COL].tolist(),
        "current_app_pred": [PHISHING_LABEL if v else BENIGN_LABEL for v in y_current],
        "meta_gate_pred": [PHISHING_LABEL if v else BENIGN_LABEL for v in y_meta],
        "meta_phishing_score": test_scores,
        "transformer_phishing_probability": test_transformer_probs,
    })
    predictions_path = os.path.join(RESULT_DIR, "external_test_predictions.csv")
    predictions_df.to_csv(predictions_path, index=False)

    summary = {
        "experiment": "phiusiil_posthoc_meta_gate_calibration",
        "data_policy": {
            "kaggle_malicious_phish_usage": (
                "Only through pre-existing artifacts_transformer. "
                "PhiUSIIL is not mixed into Kaggle 4-class training."
            ),
            "phiusiil_usage": (
                "Calibration split trains threshold/meta-gate. "
                "External test split is held out and used only for final evaluation."
            ),
            "overlap_removed_with_malicious_phish": True,
        },
        "sizes": {
            "calibration": int(len(calibration_df)),
            "external_test": int(len(test_df)),
        },
        "meta_gate": {
            "class_weight": META_CLASS_WEIGHT,
            "fp_penalty": META_FP_PENALTY,
            "selected_threshold": best_threshold,
            "feature_names": META_FEATURE_NAMES,
        },
        "current_app_hybrid": current_report,
        "meta_gate_result": meta_report,
        "manual_debug": debug_rows,
    }

    summary_path = os.path.join(RESULT_DIR, "summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    joblib.dump(meta_gate, os.path.join(ARTIFACT_DIR, "meta_gate.joblib"))
    joblib.dump(meta_scaler, os.path.join(ARTIFACT_DIR, "meta_gate_scaler.joblib"))

    config = {
        "model_family": "posthoc_phiusiil_benign_phishing_meta_gate",
        "source_artifact_dir": inference_app.ARTIFACT_DIR,
        "source_app": "app.py",
        "threshold": best_threshold["threshold"],
        "feature_names": META_FEATURE_NAMES,
        "feature_count": len(META_FEATURE_NAMES),
        "label_mapping": {
            "0": BENIGN_LABEL,
            "1": PHISHING_LABEL,
        },
        "phiusiil_label_mapping": {
            "1": "benign",
            "0": "phishing",
        },
        "artifact_files": {
            "meta_gate": "meta_gate.joblib",
            "meta_gate_scaler": "meta_gate_scaler.joblib",
            "config": "config.json",
        },
        "integration_note": (
            "To integrate with app.py later, load meta_gate/meta_gate_scaler after "
            "the existing base/Transformer prediction, recreate the same meta features, "
            "and apply score >= threshold only for benign/phishing candidate decisions."
        ),
    }
    config_path = os.path.join(ARTIFACT_DIR, "config.json")
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=False, indent=2)

    print("\n================ Threshold Selection ================")
    print("Selected threshold:", round(best_threshold["threshold"], 4))
    print("Calibration F1:", round(best_threshold["f1"], 4))
    print("Calibration benign FP rate:", round(best_threshold["benign_fp_rate"], 4))

    print("\n================ External Test Comparison ================")
    print_report(current_report)
    print_report(meta_report)

    print("\n================ Manual Debug URLs ================")
    for row in debug_rows:
        print(
            row["url"],
            "| current:",
            row["current_app_prediction"],
            "| meta:",
            row["meta_gate_prediction"],
            "| score:",
            round(row["meta_phishing_score"], 4),
        )

    print("\nSaved:")
    print(" -", threshold_path)
    print(" -", predictions_path)
    print(" -", summary_path)
    print(" -", os.path.join(ARTIFACT_DIR, "meta_gate.joblib"))
    print(" -", os.path.join(ARTIFACT_DIR, "meta_gate_scaler.joblib"))
    print(" -", config_path)


if __name__ == "__main__":
    main()
